### 회원가입
POST http://localhost:8080/auth/join
Content-Type: application/json

{
  "password" : "1234",
  "useraname" : "1234",
  "lastName" : "1234",
  "firstName" : "1234",
  "phone": "1234",
  "username": "lee222",
  "gender": "MALE",
  "email" : "wogud1513@naver.com"
}


### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "password" : "1234",
  "email" : "wogud1513@naver.com"
}