
###일기 작성
POST http://localhost:8080/diary
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJqd3RUeXBlIjoiQUNDRVNTX1RPS0VOIiwianRpIjoiNyIsInN1YiI6IjciLCJpYXQiOjE3MjM3NzUzNTIsImV4cCI6MTcyMzc3NzE1Mn0.Rvq_CEBVxKWHCMweDZjR4kbgQQviRs95TqjBWiNbOOSOtb5YWQ-k232aXk1ltojmTqXveJgITEuNXCUt7xbv1g


{
  "content": "테스트 일기야 나의 첫!",
  "type": "DAILY",
  "accessLevel": "ALL"
}

###일기 수정
PATCH http://localhost:8080/diary/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJqd3RUeXBlIjoiQUNDRVNTX1RPS0VOIiwianRpIjoiNyIsInN1YiI6IjciLCJpYXQiOjE3MjM3ODAyNzEsImV4cCI6MTcyMzc4MjA3MX0.Bn_4QRTEYm8dCwQyVldHNqwjVScwxB7orWEiBPhlX5X6BbaaGtWWI_ZGh3VITSm6sZDAnEMKCYNQnav7kNDkIg
가

{
"content": "테스트 일기야 나의 첫3!ddasd33",
"type": "DAILY",
"accessLevel": "ALL"
}

### 조회
GET http://localhost:8080/diary/1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJqd3RUeXBlIjoiQUNDRVNTX1RPS0VOIiwianRpIjoiNyIsInN1YiI6IjciLCJpYXQiOjE3MjM3ODAyNzEsImV4cCI6MTcyMzc4MjA3MX0.Bn_4QRTEYm8dCwQyVldHNqwjVScwxB7orWEiBPhlX5X6BbaaGtWWI_ZGh3VITSm6sZDAnEMKCYNQnav7kNDkIg